### ISSUE TITLE
Some controls use sharp corners even if the setting to use sharp corners is disabled

### ISSUE THREAD

**Issue by jaigak** [BreeceW/Oxidized#101]
![image](https://user-images.githubusercontent.com/45227503/125884994-fa5e2379-c88c-497d-b270-f5a368768c59.png)

**Comment by BreeceW** [comment]
This setting turns rounded corners into square corners. The inverse is not necessarily true.

The reason the corners are not rounded is because Windows was not able to round them in an attractive way. However, the good news Windows 11 has fixed this. When we do the Sun Valley redesign, most corners should be rounded.

**Comment by BreeceW** [comment]
Controls are now rounded in Oxidized Valley. The sharp corner option still exists.
