### ISSUE TITLE
WinUI 2.6 and Segoe UI Variable

### ISSUE THREAD

**Issue by AstroX809** [BreeceW/Oxidized#120]
**Description of feature or change**
Make Oxidized use WinUI 2.6 and Segoe UI Variable just like some Windows inbox apps.

**Rationale**
It'll make Oxidized much more consistent with Windows 11's Current Fluent Design Language, and make it look more native to Windows.

**Comment by BreeceW** [comment]
Yes, WinUI 2.6 (or a later version) or identical styles are planned to be added to this app. However, this is a lot more work than it seems at first glance, because many of controls are customized, and unfortunately, styling in XAML can be rather finicky.
It turns out that to get Segoe UI Variable, you target the Windows 11 SDK. It does this with `XamlAutoFontFamily`. Changing the whole app font usually doesn’t work out great, so I’d say wait a few months until the SDK is stable and we can easily target that.
If you want Segoe UI Variable today, simply open Oxidized, click Settings (Ctrl+O), click Appearance, and change Emoji font to _Segoe UI Variable Text_. The message input box will automatically change to this font, and messages will update once you scroll around or change channels. This will not set the font of the rest of the UI.

**Comment by BreeceW** [comment]
Now that Windows 11 is released, I have set the target version to Windows 11. This means that Segoe UI Variable is now in use. This will roll out as a part of a larger visual update.

**Comment by BreeceW** [comment]
Segoe UI Variable has rolled out with 1.12.7. The aforementioned visual update will come at a later date.
