### ISSUE TITLE
Oxidized adds everyone to the People App

### ISSUE THREAD

**Issue by burd1** [BreeceW/Oxidized#89]
On W10M, oxidized auto adds everyone to the people app without consent,i tried manually removing but upon opening oxidized once more it re-adds all of them back.I can untick oxidized in the contact list, but all of their display pictures still appear in the live tile making it really annoying. I literally dont know any of these people and from which group, check from the below example.The list is big so i've captured this just to show you what i mean, there are like 100 more contacts randomly added.
![wp_ss_20210521_0002](https://user-images.githubusercontent.com/5015897/119075331-3bc4e500-ba0e-11eb-896a-df4031199a51.png)

**Comment by BreeceW** [comment]
I never added a toggle because I thought the option in the People app was enough—I didn’t know that they still showed up on the Live Tile. That sounds annoying, so I’ll add some options in-app.
Oxidized syncs contacts to work with the Windows My People feature, which lets you put contacts in the taskbar. To that end, it should also sync the friends list, which it doesn’t currently. So yes, I can add an option to disable contact syncing.

**Comment by burd1** [comment]
> I never added a toggle because I thought the option in the People app was enough—I didn’t know that they still showed up on the Live Tile. That sounds annoying, so I’ll add some options in-app.
> Oxidized syncs contacts to work with the Windows My People feature, which lets you put contacts in the taskbar. To that end, it should also sync the friends list, which it doesn’t currently. So yes, I can add an option to disable contact syncing.

That would be very kind of you, thanks.

**Comment by BreeceW** [comment]
New options available in 1.11.1:
![Sync options for people: all, friends only, none](https://user-images.githubusercontent.com/18747724/119415809-5e7e2480-bcc0-11eb-95e4-64886bfc1750.png)

**Comment by burd1** [comment]
Thanks
